[project]
name = 'Quantum-Cloud-Consortium'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.quantum-algorithm-marketplace]
path = 'contracts/quantum-algorithm-marketplace.clar'
clarity_version = 3
epoch = '3.2'

[contracts.quantum-breakthrough-rewards]
path = 'contracts/quantum-breakthrough-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.quantum-resource-scheduler]
path = 'contracts/quantum-resource-scheduler.clar'
clarity_version = 3
epoch = '3.2'

[contracts.research-collaboration-engine]
path = 'contracts/research-collaboration-engine.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
